# Generated by Django 5.1 on 2024-11-28 20:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cpf', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=128)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_perfil_candidato/')),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('area_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('cpf', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=128)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_perfil_empregador/')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
            ],
        ),
    ]
