# Generated by Django 5.1 on 2024-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=30)),
                ('caracteristica_empresa', models.TextField()),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('logo', models.ImageField(null=True, upload_to='logo_empresa')),
            ],
        ),
    ]
